package routers

import (
	"online_shop/internal/configs"

	"github.com/go-chi/chi/middleware"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/cors"

	//_ "github.com/ostaltsovmichael/online_store/docs" // docs generated by Swag CLI
	httpSwagger "github.com/swaggo/http-swagger"
)

var Router = chi.NewRouter()

func GetRouters() *chi.Mux {

	Router.Use(middleware.Logger)
	cors := cors.New(cors.Options{
		AllowedOrigins:   []string{configs.Cfg.Host + "/*"},
		AllowedMethods:   []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowedHeaders:   []string{"*"},
		ExposedHeaders:   []string{"Link"},
		AllowCredentials: false,
		MaxAge:           300,
	})
	Router.Use(cors.Handler)

	Router.Get("/swagger", httpSwagger.WrapHandler)

	grupRouts("/api/v1")

	return Router
}

func grupRouts(url string) {
	Router.Route(url+"/users", UserRouter)
	Router.Route(url+"/brands", BrandRouter)
	Router.Route(url+"/devices", BrandRouter)
	Router.Route(url+"/types", BrandRouter)

}
